---
- name: Install chrony
  dnf:
    name: chrony
    state: present

- name: Switch used NTP pool to {{ chronyd_ntp_pool }}
  lineinfile:
    path: /etc/chrony.conf
    search_string: "^pool"
    line: "pool {{ chronyd_ntp_pool }} iburst"
  notify: Restart and enable chronyd
