---
- name: Install dnsmasq
  dnf:
    name: dnsmasq
    state: present

- name: "Stopper et désactiver systemd-resolved si présent"
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  ignore_errors: true
  become: true

- name: Configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    backup: yes
  notify: Restart and enable dnsmasq

- name: Open DNS firewall port
  firewalld:
    service: dns
    permanent: yes
    state: enabled
    immediate: yes

- name: Open DHCP firewall port
  firewalld:
    service: dhcp
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_facts["hostname"] in groups["dns-primary"]
