---
dnsmasq:
  upstream_dns:
    - "1.1.1.1"
    - "1.0.0.1"
  domain: "flemme.local"
  interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
  range_start: "192.168.1.100"
  range_end: "192.168.1.200"
  lease_time: "24h"
  gateway: "{{ ansible_facts['default_ipv4']['gateway'] }}"
